# Generated by Django 4.1.7 on 2023-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emplyee_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.BigIntegerField(default=''),
        ),
    ]
